---
linters:
  enable:
    - whitespace
    - misspell
    - gofumpt
    - gocritic
    - gosec
    - goimports
#    - revive
#    - nilerr
#    - bodyclose

linters-settings:
  gofumpt:
    module-path: "github.com/opsramp/tracing-proxy"
    extra-rules: true
  gocritic:
    enabled-checks:
      - ruleguard
    settings:
      ruleguard:
        rules: '${configDir}/gocritic/gocritic.go'
        failOn: dsl
