---
linters:
  enable:
    - gocritic

linters-settings:
  gocritic:
    enabled-checks:
      - ruleguard
    settings:
      ruleguard:
        rules: '${configDir}/gocritic/gocritic.go'
        failOn: dsl
