#####################
## Refinery Config ##
#####################

# ListenAddr is the IP and port on which to listen for incoming events. Incoming
# traffic is expected to be HTTP, so if using SSL put something like nginx in
# front to do the decryption.
# Should be of the form 0.0.0.0:8080
# Not eligible for live reload.
ListenAddr = "0.0.0.0:8082"

# GRPCListenAddr is the IP and port on which to listen for incoming events over
# gRPC. Incoming traffic is expected to be unencrypted, so if using SSL put
# something like nginx in front to do the decryption.
# Should be of the form 0.0.0.0:9090
# Not eligible for live reload.
GRPCListenAddr = "0.0.0.0:9090"

# PeerListenAddr is the IP and port on which to listen for traffic being
# rerouted from a peer. Peer traffic is expected to be HTTP, so if using SSL
# put something like nginx in front to do the decryption. Must be different from
# ListenAddr
# Should be of the form 0.0.0.0:8081
# Not eligible for live reload.
PeerListenAddr = "0.0.0.0:8083"
GRPCPeerListenAddr = "0.0.0.0:8084"

# CompressPeerCommunication determines whether refinery will compress span data
# it forwards to peers. If it costs money to transmit data between refinery
# instances (e.g. they're spread across AWS availability zones), then you
# almost certainly want compression enabled to reduce your bill. The option to
# disable it is provided as an escape hatch for deployments that value lower CPU
# utilization over data transfer costs.
CompressPeerCommunication = true

# APIKeys is a list of Opsramp API keys that the proxy will accept. This list
# only applies to events - other Opsramp API actions will fall through to the
# upstream API directly.
# Adding keys here causes events arriving with API keys not in this list to be
# rejected with an HTTP 401 error If an API key that is a literal '*' is in the
# list, all API keys are accepted.
# Eligible for live reload.
APIKeys = [
    # "replace-me",
    # "more-optional-keys",
    "*", # wildcard accept all keys
]

# OpsrampAPI is the URL for the upstream Opsramp API.
# Eligible for live reload.
#OpsrampAPI = "localhost:50052"
OpsrampAPI = "https://asura.opsramp.net"

#Tls Options
UseTls = true
UseTlsInsecure = false

# SendDelay is a short timer that will be triggered when a trace is complete.
# Refinery will wait this duration before actually sending the trace.  The
# reason for this short delay is to allow for small network delays or clock
# jitters to elapse and any final spans to arrive before actually sending the
# trace.  This supports duration strings with supplied units. Set to 0 for
# immediate sends.
# Eligible for live reload.
SendDelay = "2s"

# TraceTimeout is a long timer; it represents the outside boundary of how long
# to wait before sending an incomplete trace. Normally traces are sent when the
# root span arrives. Sometimes the root span never arrives (due to crashes or
# whatever), and this timer will send a trace even without having received the
# root span. If you have particularly long-lived traces you should increase this
# timer. This supports duration strings with supplied units.
# Eligible for live reload.
TraceTimeout = "60s"

# MaxBatchSize is the number of events to be included in the batch for sending
MaxBatchSize = 500

# SendTicker is a short timer; it determines the duration to use to check for traces to send
SendTicker = "100ms"

# LoggingLevel is the level above which we should log. Debug is very verbose,
# and should only be used in pre-production environments. Info is the
# recommended level. Valid options are "debug", "info", "error", and
# "panic"
# Not eligible for live reload.
LoggingLevel = "debug"

# UpstreamBufferSize and PeerBufferSize control how large of an event queue to use
# when buffering events that will be forwarded to peers or the upstream API.
UpstreamBufferSize = 10000
PeerBufferSize = 10000

# DebugServiceAddr sets the IP and port the debug service will run on
# The debug service will only run if the command line flag -d is specified
# The debug service runs on the first open port between localhost:6060 and :6069 by default
# DebugServiceAddr = "localhost:8085"

# AddHostMetadataToTrace determines whether or not to add information about
# the host that Refinery is running on to the spans that it processes.
# If enabled, information about the host will be added to each span with the
# prefix `meta.refinery.`.
# Currently the only value added is 'meta.refinery.local_hostname'.
# Not eligible for live reload
AddHostMetadataToTrace = false

# Metrics are sent to OpsRamp (The collection happens based on configuration specifie
# in OpsRampMetrics and only works when the Metrics is set to "prometheus")
SendMetricsToOpsRamp = false

############################
## Implementation Choices ##
############################

# Each of the config options below chooses an implementation of a Refinery
# component to use. Depending on the choice there may be more configuration
# required below in the section for that choice. Changing implementation choices
# requires a process restart; these changes will not be picked up by a live
# config reload. (Individual config options for a given implementation may be
# eligible for live reload).

# Collector describes which collector to use for collecting traces. The only
# current valid option is "InMemCollector".. More can be added by adding
# implementations of the Collector interface.
Collector = "InMemCollector"

#########################
## Peer Management     ##
#########################

[PeerManagement]
Type = "file"
# Peers is the list of all servers participating in this proxy cluster. Events
# will be sharded evenly across all peers based on the Trace ID. Values here
# should be the base URL used to access the peer, and should include scheme,
# hostname (or ip address) and port. All servers in the cluster should be in
# this list, including this host.
Peers = [
    "http://127.0.0.1:8084", #only grpc peer listener used
    # "http://127.0.0.1:8083",
    # "http://10.1.2.3.4:8080",
    # "http://refinery-1231:8080",
    # "http://peer-3.fqdn" // assumes port 80
]

# [PeerManagement]
# Type = "redis"
# RedisHost is is used to connect to redis for peer cluster membership management.
# Further, if the environment variable 'REFINERY_REDIS_HOST' is set it takes
# precedence and this value is ignored.
# Not eligible for live reload.
# RedisHost = "localhost:6379"

# RedisPassword is the password used to connect to redis for peer cluster membership management.
# If the environment variable 'REFINERY_REDIS_PASSWORD' is set it takes
# precedence and this value is ignored.
# Not eligible for live reload.
# RedisPassword = ""

# UseTLS enables TLS when connecting to redis for peer cluster membership management, and sets the MinVersion to 1.2.
# Not eligible for live reload.
# UseTLS = false

# UseTLSInsecure disables certificate checks
# Not eligible for live reload.
# UseTLSInsecure = false

# IdentifierInterfaceName is optional. By default, when using RedisHost, Refinery will use
# the local hostname to identify itself to other peers in Redis. If your environment
# requires that you use IPs as identifiers (for example, if peers can't resolve eachother
# by name), you can specify the network interface that Refinery is listening on here.
# Refinery will use the first unicast address that it finds on the specified network
# interface as its identifier.
# Not eligible for live reload.
# IdentifierInterfaceName = "eth0"

# UseIPV6Identifier is optional. If using IdentifierInterfaceName, Refinery will default to the first
# IPv4 unicast address it finds for the specified interface. If UseIPV6Identifier is used, will use
# the first IPV6 unicast address found.
# UseIPV6Identifier = false

# RedisIdentifier is optional. By default, when using RedisHost, Refinery will use
# the local hostname to identify itself to other peers in Redis. If your environment
# requires that you use IPs as identifiers (for example, if peers can't resolve eachother
# by name), you can specify the exact identifier (IP address, etc) to use here.
# Not eligible for live reload. Overrides IdentifierInterfaceName, if both are set.
# RedisIdentifier = "192.168.1.1"

#########################
## In-Memory Collector ##
#########################

# InMemCollector brings together all the settings that are relevant to
# collecting spans together to make traces.
[InMemCollector]

# The collection cache is used to collect all spans into a trace as well as
# remember the sampling decision for any spans that might come in after the
# trace has been marked "complete" (either by timing out or seeing the root
# span). The number of traces in the cache should be many multiples (100x to
# 1000x) of the total number of concurrently active traces (trace throughput *
# trace duration).
# Eligible for live reload. Growing the cache capacity with a live config reload
# is fine. Avoid shrinking it with a live reload (you can, but it may cause
# temporary odd sampling decisions).
CacheCapacity = 1000

# MaxAlloc is optional. If set, it must be an integer >= 0. 64-bit values are
# supported.
# If set to a non-zero value, once per tick (see SendTicker) the collector
# will compare total allocated bytes to this value. If allocation is too
# high, cache capacity will be reduced and an error will be logged.
# Useful values for this setting are generally in the range of 75%-90% of
# available system memory.
MaxAlloc = 0

###################
## Logrus Logger ##
###################

# LogrusLogger is a section of the config only used if you are using the
# LogrusLogger to send all logs to STDOUT using the logrus package. If you are
# using a different logger (eg Opsramp logger) you can leave all this
# commented out.
[LogrusLogger]

# LogFormatter specifies the log format. Accepted values are one of ["logfmt", "json"]
LogFormatter = "logfmt"

# LogOutput specifies where the logs are supposed to be written. Accpets one of ["stdout", "stderr", "file"]
LogOutput = "file"

## LogrusLogger.File - specifies configs for logs when LogOutput is set to "file"
[LogrusLogger.File]

# FileName specifies the location where the logs are supposed be stored
FileName = "/var/log/opsramp/tracing-proxy.log"

# MaxSize is the maximum size in megabytes of the log file before it gets rotated.
MaxSize = 1

# MaxBackups is the maximum number of old log files to retain.
MaxBackups = 3

# Compress determines if the rotated log files should be compressed
# using gzip.
Compress = true


#####################@##
## Prometheus Metrics ##
#####################@##

[OpsRampMetrics]
# MetricsListenAddr determines the interface and port on which Prometheus will
# listen for requests for /metrics. Must be different from the main Refinery
# listener.
# Not eligible for live reload.
MetricsListenAddr = "localhost:2112"

# OpsRampMetricsAPI is the URL for the upstream OpsRamp API.
# Not Eligible for live reload.
OpsRampMetricsAPI = "https://placeholder.api.com/"

# OpsRampTenantID is the Client or Tenant ID where the metrics are supposed to be pushed.
# Not Eligible for live reload.
OpsRampTenantID = "placeholder_tenantID"

# OpsRampMetricsAPIKey is the API key to use to send metrics to the OpsRamp.
# This is separate from the APIKeys used to authenticate regular
# traffic.
# Not Eligible for live reload.
OpsRampMetricsAPIKey = "placeholder_key"

# OpsRampMetricsAPISecret is the API Secret to use to send metrics to the OpsRamp.
# This is separate from the APISecret used to authenticate regular
# traffic.
# Not Eligible for live reload.
OpsRampMetricsAPISecret = "placeholder_secret"

# OpsRampMetricsReportingInterval is frequency specified in seconds at which
# the metrics are collected and sent to OpsRamp
# Not Eligible for live reload.
OpsRampMetricsReportingInterval = 10

# OpsRampMetricsRetryCount is the number of times we retry incase the send fails
# Not Eligible for live reload.
OpsRampMetricsRetryCount = 2

# ProxyProtocol accepts http and https
# Not Eligible for live reload.
ProxyProtocol = ""

# ProxyServer takes the proxy server address
# Not Eligible for live reload.
ProxyServer = ""

# ProxyPort takes the proxy server port
# Not Eligible for live reload.
ProxyPort = 3128

# ProxyUserName takes the proxy username
# Not Eligible for live reload.
ProxyUserName = ""

# ProxyPassword takes the proxy password
# Not Eligible for live reload.
ProxyPassword = ""

# OpsRampMetricsList is a list of regular expressions which match the metric
# names. Keep the list as small as possible since too many regular expressions can lead to bad performance.
# Internally all the regex in the list are concatinated using '|' to make the computation little faster.
# Not Eligible for live reload
OpsRampMetricsList = [".*"]
