version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    profiles:
      - redis
      - all

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "4042:8081"
    depends_on:
      - redis
    profiles:
      - redis
      - all

  tracing-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
    expose:
      - "4317"
      - "8084"
      - "8082"
    ports:
      - "8082-8084:8082"
    depends_on:
      - redis
    profiles:
      - tracing-proxy
      - all