version: '3.8'

services:
  redis:
    hostname: redis
    image: dynomitedb/redis
    expose:
      - "22122"
    profiles:
      - redis
      - all

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:22122
    ports:
      - "4042:8081"
    depends_on:
      - redis
    profiles:
      - redis
      - all

  tracing-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
    expose:
      - "4317"
      - "8084"
      - "8082"
    ports:
      - "8082-8084:8082"
    depends_on:
      - redis
    profiles:
      - tracing-proxy
      - all