---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsramp-tracing-proxy
  labels:
    app: opsramp-tracing-proxy
    appid: "${appid}"
    version: "${version}"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: opsramp-tracing-proxy
  template:
    metadata:
      labels:
        app: opsramp-tracing-proxy
        name: opsramp-tracing-proxy
        version: "${version}"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - opsramp-tracing-proxy
                topologyKey: kubernetes.io/hostname
              weight: 100
      imagePullSecrets:
        - name: quay.io
      restartPolicy: Always
      containers:
        - name: opsramp-tracing-proxy
          image: ${docker_image}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
            - name: grpc
              containerPort: 9090
              protocol: TCP
            - name: peer
              containerPort: 8083
              protocol: TCP
            - containerPort: 8084
              name: grpc-peer
          resources:
            requests:
              memory: "2048Mi"
              cpu: "2"
            limits:
              memory: "8096Mi"
              cpu: "4"
          volumeMounts:
            - name: tracing-configs
              mountPath: /config/data
      volumes:
        - configMap:
            name: tracing-proxy-cm
          name: tracing-configs

