---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsramp-tracing-proxy
  namespace: opsramp-tracing-proxy
  labels:
    app: opsramp-tracing-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opsramp-tracing-proxy
  template:
    metadata:
      labels:
        app: opsramp-tracing-proxy
    spec:
      containers:
        - name: opsramp-tracing-proxy
          image: us-docker.pkg.dev/opsramp-registry/agent-images/trace-proxy
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
            - name: grpc
              containerPort: 9090
              protocol: TCP
            - name: peer
              containerPort: 8083
              protocol: TCP
            - containerPort: 8084
              name: grpc-peer
          resources:
            requests:
              memory: "2048Mi"
              cpu: "2"
            limits:
              memory: "8096Mi"
              cpu: "4"
          volumeMounts:
            - name: opsramp-tracing-rules
              mountPath: /etc/tracing-proxy/rules.yaml
              subPath: rules.yaml
              readOnly: true
            - name: opsramp-tracing-config
              mountPath: /etc/tracing-proxy/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: elastic-cache
              mountPath: /config/data
            - name: creds
              mountPath: /config/data
      volumes:
        - configMap:
            name: opsramp-tracing-proxy-rules
          name: opsramp-tracing-rules
        - configMap:
            name: opsramp-tracing-proxy-config
          name: opsramp-tracing-config
        - configMap:
            name: tracing-proxy-cm
          name: elastic-cache
        - configMap:
            name: opsramp-tracing-proxy-creds
          name: creds

