---
apiVersion: v1
kind: Service
metadata:
  name: opsramp-tracing-proxy
spec:
  selector:
    app: opsramp-tracing-proxy
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: grpc
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: http
    - protocol: TCP
      port: 8083
      targetPort: 8083
      name: peer
    - protocol: TCP
      port: 8084
      targetPort: 8084
      name: grpc-peer