---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsramp-tracing-proxy
  labels:
    app: opsramp-tracing-proxy
    appid: "${appid}"
    version: "${version}"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: opsramp-tracing-proxy
  template:
    metadata:
      labels:
        app: opsramp-tracing-proxy
        name: opsramp-tracing-proxy
        version: "${version}"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - opsramp-tracing-proxy
                topologyKey: kubernetes.io/hostname
              weight: 100
      imagePullSecrets:
        - name: quay.io
      restartPolicy: Always
      containers:
        - name: opsramp-tracing-proxy
          image: ${docker_image}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
            - name: grpc
              containerPort: 9090
              protocol: TCP
            - name: peer
              containerPort: 8083
              protocol: TCP
            - containerPort: 8084
              name: grpc-peer
          volumeMounts:
            - name: tracing-configs
              mountPath: /config/data
            - name: opsramp-tracing-rules
              mountPath: /etc/tracing-proxy/rules.yaml
              subPath: rules.yaml
              readOnly: true
            - name: opsramp-tracing-config
              mountPath: /etc/tracing-proxy/config.yaml
              subPath: config.yaml
              readOnly: true
          env:
            - name: CONTAINER_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: opsramp-tracing-proxy
                  resource: requests.cpu
            - name: CONTAINER_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: opsramp-tracing-proxy
                  resource: limits.cpu
            - name: CONTAINER_MEM_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: opsramp-tracing-proxy
                  resource: requests.memory
            - name: CONTAINER_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: opsramp-tracing-proxy
                  resource: limits.memory
      volumes:
        - configMap:
            name: tracing-proxy-cm
          name: tracing-configs
        - configMap:
            name: opsramp-tracing-proxy-rules
          name: opsramp-tracing-rules
        - configMap:
            name: opsramp-tracing-proxy-config
          name: opsramp-tracing-config

