apiVersion: v1
kind: Namespace
metadata:
  name: opsramp-tracing-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsramp-tracing-proxy
  namespace: opsramp-tracing-proxy
  labels:
    app: opsramp-tracing-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opsramp-tracing-proxy
  template:
    metadata:
      labels:
        app: opsramp-tracing-proxy
    spec:
      containers:
        - name: opsramp-tracing-proxy
          image: lokeshopsramp/tracing-proxy
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "2048Mi"
              cpu: "2"
            limits:
              memory: "8096Mi"
              cpu: "4"
          volumeMounts:
            - name: opsramp-tracing-rules
              mountPath: /etc/tracing-proxy/rules.toml
              subPath: rules.toml
              readOnly: true
            - name: opsramp-tracing-config
              mountPath: /etc/tracing-proxy/config.toml
              subPath: config.toml
              readOnly: true
      volumes:
        - configMap:
            name: opsramp-tracing-proxy-rules
          name: opsramp-tracing-rules
        - configMap:
            name: opsramp-tracing-proxy-config
          name: opsramp-tracing-config

---
apiVersion: v1
kind: Service
metadata:
  name: opsramp-tracing-proxy
  namespace: opsramp-tracing-proxy
spec:
  selector:
    app: opsramp-tracing-proxy
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
