on:
  release:
    types: [ created ]
name: Handle Release
jobs:
  generate-deb:
    name: Create debian package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: addnab/docker-run-action@v3
        with:
          image: golang:buster
          options: -v ${{ github.workspace }}:/tracing-proxy --env IS_GITHUB_ACTION=true --env VERSION_TAG=${{ github.event.release.tag_name }}
          run: |
            cd tracing-proxy
            /bin/bash build/vm/tracing-deb/script.sh
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "build/vm/tracing-deb/output/*"

  generate-rpm:
    name: Create RPM package
    runs-on: ubuntu-latest
    container:
      image: centos:centos7
      options: "--entrypoint /bin/bash"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: addnab/docker-run-action@v3
        with:
          image: rockylinux:8
          options: -v ${{ github.workspace }}:/tracing-proxy --env IS_GITHUB_ACTION=true --env VERSION_TAG=${{ github.event.release.tag_name }}
          run: |
            yum install golang -y
            cd tracing-proxy
            /bin/bash build/vm/tracing-rpm/script.sh
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "/root/rpmbuild/RPMS/x86_64/*"