on:
  release:
    types: [ created ]
name: Handle Release
jobs:
  generate-deb:
    name: Create debian package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: addnab/docker-run-action@v3
        with:
          image: golang:1.22.5-bullseye
          options: -v ${{ github.workspace }}:${{ github.workspace }} --env IS_GITHUB_ACTION=true --env VERSION_TAG=${{ github.event.release.tag_name }}
          run: |
            cd ${{ github.workspace }}
            /bin/bash build/vm/tracing-deb/script.sh
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "build/vm/tracing-deb/output/*"

  generate-rpm:
    name: Create RPM package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: addnab/docker-run-action@v3
        with:
          image: centos:6
          options: -v ${{ github.workspace }}:${{ github.workspace }} --env IS_GITHUB_ACTION=true --env VERSION_TAG=${{ github.event.release.tag_name }}
          run: |
            # change the mirrors to vault mirros since CentOS-6 has reached EOL
            sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
            sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
            
            # manually download and install golang
            curl -L -O https://go.dev/dl/go1.22.2.linux-amd64.tar.gz
            rm -rf /usr/local/go && tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz
            
            # setup env and build the rpm package
            cd ${{ github.workspace }}
            PATH=$PATH:/usr/local/go/bin /bin/bash build/vm/tracing-rpm/script.sh
            mkdir -p ${{ github.workspace }}/output
            cp -r /root/rpmbuild/RPMS/x86_64/* ${{ github.workspace }}/output
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "${{ github.workspace }}/output/*"

  oci-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: LokeshOpsramp
          password: ${{ secrets.SUPERSECRETPASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/LokeshOpsramp/trace-proxy
          tags: |
            type=semver,pattern=${{ github.event.release.tag_name }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  oci-container-image-hpe-ccp:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: LokeshOpsramp
          password: ${{ secrets.SUPERSECRETPASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/LokeshOpsramp/trace-proxy
          flavor: |
            latest=true
            suffix=-hpe,onlatest=true
          tags: |
            type=semver,pattern=${{ github.event.release.tag_name }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          file: "deploy/Dockerfile"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
